/*
-- Query: SELECT * FROM db_projeto.tb_competencia
LIMIT 0, 1000

-- Date: 2016-08-13 15:34
*/
INSERT INTO `tb_competencia` (`ID_COMPETENCIA`,`descricao`,`nome`,`ID_TIPO_COMPETENCIA`) VALUES (1,NULL,'DESENVOLVIMENTO JAVA',2);
INSERT INTO `tb_competencia` (`ID_COMPETENCIA`,`descricao`,`nome`,`ID_TIPO_COMPETENCIA`) VALUES (2,NULL,'DESENVOLVIMENTO C#',2);
INSERT INTO `tb_competencia` (`ID_COMPETENCIA`,`descricao`,`nome`,`ID_TIPO_COMPETENCIA`) VALUES (3,NULL,'COMUNICAÇÃO',1);
INSERT INTO `tb_competencia` (`ID_COMPETENCIA`,`descricao`,`nome`,`ID_TIPO_COMPETENCIA`) VALUES (4,NULL,'LIDERANÇA',1);
INSERT INTO `tb_competencia` (`ID_COMPETENCIA`,`descricao`,`nome`,`ID_TIPO_COMPETENCIA`) VALUES (5,NULL,'CRIATIVIDADE E INOVAÇÃO',1);
INSERT INTO `tb_competencia` (`ID_COMPETENCIA`,`descricao`,`nome`,`ID_TIPO_COMPETENCIA`) VALUES (6,NULL,'ADMINISTRAÇÃO BANCO DE DADOS',2);
INSERT INTO `tb_competencia` (`ID_COMPETENCIA`,`descricao`,`nome`,`ID_TIPO_COMPETENCIA`) VALUES (7,NULL,'REDES DE COMPUTADORES',2);
INSERT INTO `tb_competencia` (`ID_COMPETENCIA`,`descricao`,`nome`,`ID_TIPO_COMPETENCIA`) VALUES (8,NULL,'CSS/HTML/JAVASCRIPT',2);
