INSERT INTO TB_ESCALA (NOME,VALOR) VALUES ('insuficiente',1);
INSERT INTO TB_ESCALA (NOME,VALOR) VALUES ('ruim',2);
INSERT INTO TB_ESCALA (NOME,VALOR) VALUES ('bom',3);
INSERT INTO TB_ESCALA (NOME,VALOR) VALUES ('otimo',4);
INSERT INTO TB_ESCALA (NOME,VALOR) VALUES ('exelente',5);
