/*
-- Query: SELECT * FROM db_projeto.tb_competencia
LIMIT 0, 1000

-- Date: 2016-10-06 10:45
*/
INSERT INTO `tb_competencia` (`ID_COMPETENCIA`,`descricao`,`nome`,`ID_TIPO_COMPETENCIA`) VALUES (1,'BASE DO DESENVOLVIMENTO JAVA','ORIENTAÇÃO A OBJETOS',2);
INSERT INTO `tb_competencia` (`ID_COMPETENCIA`,`descricao`,`nome`,`ID_TIPO_COMPETENCIA`) VALUES (2,'ALSDFADSFA','LINGUAGEM C#',2);
INSERT INTO `tb_competencia` (`ID_COMPETENCIA`,`descricao`,`nome`,`ID_TIPO_COMPETENCIA`) VALUES (3,'AASDFASDF','LINGUAGEM JAVA',2);
INSERT INTO `tb_competencia` (`ID_COMPETENCIA`,`descricao`,`nome`,`ID_TIPO_COMPETENCIA`) VALUES (4,'LSÇDAJFLKÇASDJÇAS','DESENVOLVIMENTO JAVASCRIPT',2);
