INSERT INTO TB_PERMISSAO (ID_PERMISSAO,role) VALUES (1,'ROLE_ADMIN');
INSERT INTO TB_PERMISSAO (ID_PERMISSAO,role) VALUES (3,'ROLE_AVALIADO');
INSERT INTO TB_PERMISSAO (ID_PERMISSAO,role) VALUES (2,'ROLE_LIDER');
