/*
-- Query: SELECT * FROM db_projeto.tb_departamento
LIMIT 0, 1000

-- Date: 2016-10-06 10:44
*/
INSERT INTO `tb_departamento` (`ID_DEPARTAMENTO`,`NOME_DEPARTAMENTO`,`ID_DEPARTAMENTO_PAI`,`ID_ORGANIZACAO`) VALUES (1,'DIRETORIA',NULL,1);
INSERT INTO `tb_departamento` (`ID_DEPARTAMENTO`,`NOME_DEPARTAMENTO`,`ID_DEPARTAMENTO_PAI`,`ID_ORGANIZACAO`) VALUES (2,'SUB DIRETORIA',1,1);
INSERT INTO `tb_departamento` (`ID_DEPARTAMENTO`,`NOME_DEPARTAMENTO`,`ID_DEPARTAMENTO_PAI`,`ID_ORGANIZACAO`) VALUES (3,'SUB DEPARTAMENTO 2',NULL,1);
INSERT INTO `tb_departamento` (`ID_DEPARTAMENTO`,`NOME_DEPARTAMENTO`,`ID_DEPARTAMENTO_PAI`,`ID_ORGANIZACAO`) VALUES (4,'kjsaDLKasflçsadjlfew',NULL,1);
